// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: abci.proto

package heimdall

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BlockIDFlag indicates whether a validator voted for a block, was absent, or voted nil.
type BlockIDFlag int32

const (
	BlockIDFlag_BLOCK_ID_FLAG_UNKNOWN BlockIDFlag = 0
	BlockIDFlag_BLOCK_ID_FLAG_ABSENT  BlockIDFlag = 1
	BlockIDFlag_BLOCK_ID_FLAG_COMMIT  BlockIDFlag = 2
	BlockIDFlag_BLOCK_ID_FLAG_NIL     BlockIDFlag = 3
)

// Enum value maps for BlockIDFlag.
var (
	BlockIDFlag_name = map[int32]string{
		0: "BLOCK_ID_FLAG_UNKNOWN",
		1: "BLOCK_ID_FLAG_ABSENT",
		2: "BLOCK_ID_FLAG_COMMIT",
		3: "BLOCK_ID_FLAG_NIL",
	}
	BlockIDFlag_value = map[string]int32{
		"BLOCK_ID_FLAG_UNKNOWN": 0,
		"BLOCK_ID_FLAG_ABSENT":  1,
		"BLOCK_ID_FLAG_COMMIT":  2,
		"BLOCK_ID_FLAG_NIL":     3,
	}
)

func (x BlockIDFlag) Enum() *BlockIDFlag {
	p := new(BlockIDFlag)
	*p = x
	return p
}

func (x BlockIDFlag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BlockIDFlag) Descriptor() protoreflect.EnumDescriptor {
	return file_abci_proto_enumTypes[0].Descriptor()
}

func (BlockIDFlag) Type() protoreflect.EnumType {
	return &file_abci_proto_enumTypes[0]
}

func (x BlockIDFlag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BlockIDFlag.Descriptor instead.
func (BlockIDFlag) EnumDescriptor() ([]byte, []int) {
	return file_abci_proto_rawDescGZIP(), []int{0}
}

// Validator contains the address and voting power of a validator.
type Validator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Power         int64                  `protobuf:"varint,3,opt,name=power,proto3" json:"power,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Validator) Reset() {
	*x = Validator{}
	mi := &file_abci_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Validator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Validator) ProtoMessage() {}

func (x *Validator) ProtoReflect() protoreflect.Message {
	mi := &file_abci_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Validator.ProtoReflect.Descriptor instead.
func (*Validator) Descriptor() ([]byte, []int) {
	return file_abci_proto_rawDescGZIP(), []int{0}
}

func (x *Validator) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Validator) GetPower() int64 {
	if x != nil {
		return x.Power
	}
	return 0
}

// ExtendedVoteInfo contains validator info, vote extension, and signature.
type ExtendedVoteInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Validator          *Validator             `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	VoteExtension      []byte                 `protobuf:"bytes,3,opt,name=vote_extension,json=voteExtension,proto3" json:"vote_extension,omitempty"`
	ExtensionSignature []byte                 `protobuf:"bytes,4,opt,name=extension_signature,json=extensionSignature,proto3" json:"extension_signature,omitempty"`
	BlockIdFlag        BlockIDFlag            `protobuf:"varint,5,opt,name=block_id_flag,json=blockIdFlag,proto3,enum=panoptichain.heimdall.BlockIDFlag" json:"block_id_flag,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ExtendedVoteInfo) Reset() {
	*x = ExtendedVoteInfo{}
	mi := &file_abci_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendedVoteInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendedVoteInfo) ProtoMessage() {}

func (x *ExtendedVoteInfo) ProtoReflect() protoreflect.Message {
	mi := &file_abci_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendedVoteInfo.ProtoReflect.Descriptor instead.
func (*ExtendedVoteInfo) Descriptor() ([]byte, []int) {
	return file_abci_proto_rawDescGZIP(), []int{1}
}

func (x *ExtendedVoteInfo) GetValidator() *Validator {
	if x != nil {
		return x.Validator
	}
	return nil
}

func (x *ExtendedVoteInfo) GetVoteExtension() []byte {
	if x != nil {
		return x.VoteExtension
	}
	return nil
}

func (x *ExtendedVoteInfo) GetExtensionSignature() []byte {
	if x != nil {
		return x.ExtensionSignature
	}
	return nil
}

func (x *ExtendedVoteInfo) GetBlockIdFlag() BlockIDFlag {
	if x != nil {
		return x.BlockIdFlag
	}
	return BlockIDFlag_BLOCK_ID_FLAG_UNKNOWN
}

// ExtendedCommitInfo contains the round and all extended vote info.
type ExtendedCommitInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Round         int32                  `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	Votes         []*ExtendedVoteInfo    `protobuf:"bytes,2,rep,name=votes,proto3" json:"votes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendedCommitInfo) Reset() {
	*x = ExtendedCommitInfo{}
	mi := &file_abci_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendedCommitInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendedCommitInfo) ProtoMessage() {}

func (x *ExtendedCommitInfo) ProtoReflect() protoreflect.Message {
	mi := &file_abci_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendedCommitInfo.ProtoReflect.Descriptor instead.
func (*ExtendedCommitInfo) Descriptor() ([]byte, []int) {
	return file_abci_proto_rawDescGZIP(), []int{2}
}

func (x *ExtendedCommitInfo) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *ExtendedCommitInfo) GetVotes() []*ExtendedVoteInfo {
	if x != nil {
		return x.Votes
	}
	return nil
}

var File_abci_proto protoreflect.FileDescriptor

const file_abci_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"abci.proto\x12\x15panoptichain.heimdall\";\n" +
	"\tValidator\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12\x14\n" +
	"\x05power\x18\x03 \x01(\x03R\x05power\"\xf2\x01\n" +
	"\x10ExtendedVoteInfo\x12>\n" +
	"\tvalidator\x18\x01 \x01(\v2 .panoptichain.heimdall.ValidatorR\tvalidator\x12%\n" +
	"\x0evote_extension\x18\x03 \x01(\fR\rvoteExtension\x12/\n" +
	"\x13extension_signature\x18\x04 \x01(\fR\x12extensionSignature\x12F\n" +
	"\rblock_id_flag\x18\x05 \x01(\x0e2\".panoptichain.heimdall.BlockIDFlagR\vblockIdFlag\"i\n" +
	"\x12ExtendedCommitInfo\x12\x14\n" +
	"\x05round\x18\x01 \x01(\x05R\x05round\x12=\n" +
	"\x05votes\x18\x02 \x03(\v2'.panoptichain.heimdall.ExtendedVoteInfoR\x05votes*s\n" +
	"\vBlockIDFlag\x12\x19\n" +
	"\x15BLOCK_ID_FLAG_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14BLOCK_ID_FLAG_ABSENT\x10\x01\x12\x18\n" +
	"\x14BLOCK_ID_FLAG_COMMIT\x10\x02\x12\x15\n" +
	"\x11BLOCK_ID_FLAG_NIL\x10\x03B2Z0github.com/0xPolygon/panoptichain/proto/heimdallb\x06proto3"

var (
	file_abci_proto_rawDescOnce sync.Once
	file_abci_proto_rawDescData []byte
)

func file_abci_proto_rawDescGZIP() []byte {
	file_abci_proto_rawDescOnce.Do(func() {
		file_abci_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_abci_proto_rawDesc), len(file_abci_proto_rawDesc)))
	})
	return file_abci_proto_rawDescData
}

var file_abci_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_abci_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_abci_proto_goTypes = []any{
	(BlockIDFlag)(0),           // 0: panoptichain.heimdall.BlockIDFlag
	(*Validator)(nil),          // 1: panoptichain.heimdall.Validator
	(*ExtendedVoteInfo)(nil),   // 2: panoptichain.heimdall.ExtendedVoteInfo
	(*ExtendedCommitInfo)(nil), // 3: panoptichain.heimdall.ExtendedCommitInfo
}
var file_abci_proto_depIdxs = []int32{
	1, // 0: panoptichain.heimdall.ExtendedVoteInfo.validator:type_name -> panoptichain.heimdall.Validator
	0, // 1: panoptichain.heimdall.ExtendedVoteInfo.block_id_flag:type_name -> panoptichain.heimdall.BlockIDFlag
	2, // 2: panoptichain.heimdall.ExtendedCommitInfo.votes:type_name -> panoptichain.heimdall.ExtendedVoteInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_abci_proto_init() }
func file_abci_proto_init() {
	if File_abci_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_abci_proto_rawDesc), len(file_abci_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_abci_proto_goTypes,
		DependencyIndexes: file_abci_proto_depIdxs,
		EnumInfos:         file_abci_proto_enumTypes,
		MessageInfos:      file_abci_proto_msgTypes,
	}.Build()
	File_abci_proto = out.File
	file_abci_proto_goTypes = nil
	file_abci_proto_depIdxs = nil
}
