// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: sidetxs.proto

package heimdall

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Vote represents the result of a side transaction validation.
type Vote int32

const (
	Vote_VOTE_UNSPECIFIED Vote = 0
	Vote_VOTE_YES         Vote = 1
	Vote_VOTE_NO          Vote = 2
)

// Enum value maps for Vote.
var (
	Vote_name = map[int32]string{
		0: "VOTE_UNSPECIFIED",
		1: "VOTE_YES",
		2: "VOTE_NO",
	}
	Vote_value = map[string]int32{
		"VOTE_UNSPECIFIED": 0,
		"VOTE_YES":         1,
		"VOTE_NO":          2,
	}
)

func (x Vote) Enum() *Vote {
	p := new(Vote)
	*p = x
	return p
}

func (x Vote) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Vote) Descriptor() protoreflect.EnumDescriptor {
	return file_sidetxs_proto_enumTypes[0].Descriptor()
}

func (Vote) Type() protoreflect.EnumType {
	return &file_sidetxs_proto_enumTypes[0]
}

func (x Vote) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Vote.Descriptor instead.
func (Vote) EnumDescriptor() ([]byte, []int) {
	return file_sidetxs_proto_rawDescGZIP(), []int{0}
}

// SideTxResponse contains a transaction hash and the vote result.
type SideTxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        []byte                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Result        Vote                   `protobuf:"varint,2,opt,name=result,proto3,enum=panoptichain.heimdall.Vote" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SideTxResponse) Reset() {
	*x = SideTxResponse{}
	mi := &file_sidetxs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SideTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SideTxResponse) ProtoMessage() {}

func (x *SideTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sidetxs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SideTxResponse.ProtoReflect.Descriptor instead.
func (*SideTxResponse) Descriptor() ([]byte, []int) {
	return file_sidetxs_proto_rawDescGZIP(), []int{0}
}

func (x *SideTxResponse) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *SideTxResponse) GetResult() Vote {
	if x != nil {
		return x.Result
	}
	return Vote_VOTE_UNSPECIFIED
}

// MilestoneProposition contains the block hashes and metadata for a milestone.
type MilestoneProposition struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BlockHashes      [][]byte               `protobuf:"bytes,1,rep,name=block_hashes,json=blockHashes,proto3" json:"block_hashes,omitempty"`
	StartBlockNumber uint64                 `protobuf:"varint,2,opt,name=start_block_number,json=startBlockNumber,proto3" json:"start_block_number,omitempty"`
	ParentHash       []byte                 `protobuf:"bytes,3,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	BlockTds         []uint64               `protobuf:"varint,4,rep,packed,name=block_tds,json=blockTds,proto3" json:"block_tds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MilestoneProposition) Reset() {
	*x = MilestoneProposition{}
	mi := &file_sidetxs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MilestoneProposition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MilestoneProposition) ProtoMessage() {}

func (x *MilestoneProposition) ProtoReflect() protoreflect.Message {
	mi := &file_sidetxs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MilestoneProposition.ProtoReflect.Descriptor instead.
func (*MilestoneProposition) Descriptor() ([]byte, []int) {
	return file_sidetxs_proto_rawDescGZIP(), []int{1}
}

func (x *MilestoneProposition) GetBlockHashes() [][]byte {
	if x != nil {
		return x.BlockHashes
	}
	return nil
}

func (x *MilestoneProposition) GetStartBlockNumber() uint64 {
	if x != nil {
		return x.StartBlockNumber
	}
	return 0
}

func (x *MilestoneProposition) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *MilestoneProposition) GetBlockTds() []uint64 {
	if x != nil {
		return x.BlockTds
	}
	return nil
}

// VoteExtension contains validator vote extension data including milestone propositions.
type VoteExtension struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	BlockHash            []byte                 `protobuf:"bytes,1,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	Height               int64                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	SideTxResponses      []*SideTxResponse      `protobuf:"bytes,3,rep,name=side_tx_responses,json=sideTxResponses,proto3" json:"side_tx_responses,omitempty"`
	MilestoneProposition *MilestoneProposition  `protobuf:"bytes,4,opt,name=milestone_proposition,json=milestoneProposition,proto3" json:"milestone_proposition,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *VoteExtension) Reset() {
	*x = VoteExtension{}
	mi := &file_sidetxs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteExtension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteExtension) ProtoMessage() {}

func (x *VoteExtension) ProtoReflect() protoreflect.Message {
	mi := &file_sidetxs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteExtension.ProtoReflect.Descriptor instead.
func (*VoteExtension) Descriptor() ([]byte, []int) {
	return file_sidetxs_proto_rawDescGZIP(), []int{2}
}

func (x *VoteExtension) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *VoteExtension) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *VoteExtension) GetSideTxResponses() []*SideTxResponse {
	if x != nil {
		return x.SideTxResponses
	}
	return nil
}

func (x *VoteExtension) GetMilestoneProposition() *MilestoneProposition {
	if x != nil {
		return x.MilestoneProposition
	}
	return nil
}

var File_sidetxs_proto protoreflect.FileDescriptor

const file_sidetxs_proto_rawDesc = "" +
	"\n" +
	"\rsidetxs.proto\x12\x15panoptichain.heimdall\"^\n" +
	"\x0eSideTxResponse\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\fR\x06txHash\x123\n" +
	"\x06result\x18\x02 \x01(\x0e2\x1b.panoptichain.heimdall.VoteR\x06result\"\xa5\x01\n" +
	"\x14MilestoneProposition\x12!\n" +
	"\fblock_hashes\x18\x01 \x03(\fR\vblockHashes\x12,\n" +
	"\x12start_block_number\x18\x02 \x01(\x04R\x10startBlockNumber\x12\x1f\n" +
	"\vparent_hash\x18\x03 \x01(\fR\n" +
	"parentHash\x12\x1b\n" +
	"\tblock_tds\x18\x04 \x03(\x04R\bblockTds\"\xfb\x01\n" +
	"\rVoteExtension\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x01 \x01(\fR\tblockHash\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x03R\x06height\x12Q\n" +
	"\x11side_tx_responses\x18\x03 \x03(\v2%.panoptichain.heimdall.SideTxResponseR\x0fsideTxResponses\x12`\n" +
	"\x15milestone_proposition\x18\x04 \x01(\v2+.panoptichain.heimdall.MilestonePropositionR\x14milestoneProposition*7\n" +
	"\x04Vote\x12\x14\n" +
	"\x10VOTE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bVOTE_YES\x10\x01\x12\v\n" +
	"\aVOTE_NO\x10\x02B2Z0github.com/0xPolygon/panoptichain/proto/heimdallb\x06proto3"

var (
	file_sidetxs_proto_rawDescOnce sync.Once
	file_sidetxs_proto_rawDescData []byte
)

func file_sidetxs_proto_rawDescGZIP() []byte {
	file_sidetxs_proto_rawDescOnce.Do(func() {
		file_sidetxs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sidetxs_proto_rawDesc), len(file_sidetxs_proto_rawDesc)))
	})
	return file_sidetxs_proto_rawDescData
}

var file_sidetxs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sidetxs_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sidetxs_proto_goTypes = []any{
	(Vote)(0),                    // 0: panoptichain.heimdall.Vote
	(*SideTxResponse)(nil),       // 1: panoptichain.heimdall.SideTxResponse
	(*MilestoneProposition)(nil), // 2: panoptichain.heimdall.MilestoneProposition
	(*VoteExtension)(nil),        // 3: panoptichain.heimdall.VoteExtension
}
var file_sidetxs_proto_depIdxs = []int32{
	0, // 0: panoptichain.heimdall.SideTxResponse.result:type_name -> panoptichain.heimdall.Vote
	1, // 1: panoptichain.heimdall.VoteExtension.side_tx_responses:type_name -> panoptichain.heimdall.SideTxResponse
	2, // 2: panoptichain.heimdall.VoteExtension.milestone_proposition:type_name -> panoptichain.heimdall.MilestoneProposition
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sidetxs_proto_init() }
func file_sidetxs_proto_init() {
	if File_sidetxs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sidetxs_proto_rawDesc), len(file_sidetxs_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sidetxs_proto_goTypes,
		DependencyIndexes: file_sidetxs_proto_depIdxs,
		EnumInfos:         file_sidetxs_proto_enumTypes,
		MessageInfos:      file_sidetxs_proto_msgTypes,
	}.Build()
	File_sidetxs_proto = out.File
	file_sidetxs_proto_goTypes = nil
	file_sidetxs_proto_depIdxs = nil
}
