version: "3"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9091:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana

  panoptichain:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: panoptichain
    ports:
      - 9090:9090
    environment:
      - PANOPTICHAIN_HTTP_ADDRESS=0.0.0.0
      - PANOPTICHAIN_HTTP_PORT=9090
    volumes:
      - ./config.yml:/etc/panoptichain/config.yml

volumes:
  grafana:
