// Code generated by "stringer -type=ObservableTopic"; DO NOT EDIT.

package topics

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AccountBalances-0]
	_ = x[BlockInterval-1]
	_ = x[BorMissedBlockProposal-2]
	_ = x[BorStateSync-3]
	_ = x[BridgeEvent-4]
	_ = x[BridgeEventTimes-5]
	_ = x[Checkpoint-6]
	_ = x[CheckpointSignatures-7]
	_ = x[ClaimEvent-8]
	_ = x[ClaimEventTimes-9]
	_ = x[DepositCounts-10]
	_ = x[ExchangeRate-11]
	_ = x[ExitRoots-12]
	_ = x[FinalizedHeight-13]
	_ = x[HashDivergence-14]
	_ = x[HeimdallBlockInterval-15]
	_ = x[HeimdallMissedBlockProposal-16]
	_ = x[Milestone-17]
	_ = x[MissedCheckpointProposal-18]
	_ = x[NewEVMBlock-19]
	_ = x[NewHeimdallBlock-20]
	_ = x[ProofRequest-21]
	_ = x[RefreshStateTime-22]
	_ = x[Reorg-23]
	_ = x[RollupManager-24]
	_ = x[SensorBlockEvents-25]
	_ = x[SensorBlocks-26]
	_ = x[Span-27]
	_ = x[StolenBlock-28]
	_ = x[System-29]
	_ = x[TimeToFinalized-30]
	_ = x[TimeToMine-31]
	_ = x[TransactionPool-32]
	_ = x[TrustedBatch-33]
	_ = x[ValidatorWallet-34]
	_ = x[ZkEVMBatches-35]
}

const _ObservableTopic_name = "AccountBalancesBlockIntervalBorMissedBlockProposalBorStateSyncBridgeEventBridgeEventTimesCheckpointCheckpointSignaturesClaimEventClaimEventTimesDepositCountsExchangeRateExitRootsFinalizedHeightHashDivergenceHeimdallBlockIntervalHeimdallMissedBlockProposalMilestoneMissedCheckpointProposalNewEVMBlockNewHeimdallBlockProofRequestRefreshStateTimeReorgRollupManagerSensorBlockEventsSensorBlocksSpanStolenBlockSystemTimeToFinalizedTimeToMineTransactionPoolTrustedBatchValidatorWalletZkEVMBatches"

var _ObservableTopic_index = [...]uint16{0, 15, 28, 50, 62, 73, 89, 99, 119, 129, 144, 157, 169, 178, 193, 207, 228, 255, 264, 288, 299, 315, 327, 343, 348, 361, 378, 390, 394, 405, 411, 426, 436, 451, 463, 478, 490}

func (i ObservableTopic) String() string {
	if i < 0 || i >= ObservableTopic(len(_ObservableTopic_index)-1) {
		return "ObservableTopic(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ObservableTopic_name[_ObservableTopic_index[i]:_ObservableTopic_index[i+1]]
}
