// Code generated by "stringer -type=ObservableTopic"; DO NOT EDIT.

package topics

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AccountBalances-0]
	_ = x[AccountTxs-1]
	_ = x[AggchainEvent-2]
	_ = x[BlockInterval-3]
	_ = x[BorMissedBlockProposal-4]
	_ = x[BorStateSync-5]
	_ = x[BridgeEvent-6]
	_ = x[BridgeEventTimes-7]
	_ = x[Checkpoint-8]
	_ = x[CheckpointSignatures-9]
	_ = x[ClaimEvent-10]
	_ = x[ClaimEventTimes-11]
	_ = x[DepositCounts-12]
	_ = x[ExchangeRate-13]
	_ = x[ExitRoots-14]
	_ = x[FinalizedHeight-15]
	_ = x[Grafana-16]
	_ = x[HashDivergence-17]
	_ = x[HeimdallBlockInterval-18]
	_ = x[Milestone-19]
	_ = x[MissedCheckpointProposal-20]
	_ = x[NewEVMBlock-21]
	_ = x[NewHeimdallBlock-22]
	_ = x[ProofRequest-23]
	_ = x[RefreshStateTime-24]
	_ = x[Reorg-25]
	_ = x[RollupManager-26]
	_ = x[SensorBlockEvents-27]
	_ = x[SensorBlocks-28]
	_ = x[Span-29]
	_ = x[StakeManager-30]
	_ = x[SPOLController-31]
	_ = x[StolenBlock-32]
	_ = x[System-33]
	_ = x[TimeToFinalized-34]
	_ = x[TimeToMine-35]
	_ = x[TransactionPool-36]
	_ = x[TrustedBatch-37]
	_ = x[ValidatorWallet-38]
	_ = x[ValidatorSet-39]
	_ = x[MissedVote-40]
	_ = x[ZkEVMBatches-41]
	_ = x[StakingEvents-42]
	_ = x[BufferedCheckpoint-43]
	_ = x[MilestoneLatest-44]
	_ = x[ActiveSpan-45]
	_ = x[RequesterUsage-46]
	_ = x[HeimdallMissedBlockProposal-47]
}

const _ObservableTopic_name = "AccountBalancesAccountTxsAggchainEventBlockIntervalBorMissedBlockProposalBorStateSyncBridgeEventBridgeEventTimesCheckpointCheckpointSignaturesClaimEventClaimEventTimesDepositCountsExchangeRateExitRootsFinalizedHeightGrafanaHashDivergenceHeimdallBlockIntervalMilestoneMissedCheckpointProposalNewEVMBlockNewHeimdallBlockProofRequestRefreshStateTimeReorgRollupManagerSensorBlockEventsSensorBlocksSpanStakeManagerSPOLControllerStolenBlockSystemTimeToFinalizedTimeToMineTransactionPoolTrustedBatchValidatorWalletValidatorSetMissedVoteZkEVMBatchesStakingEventsBufferedCheckpointMilestoneLatestActiveSpanRequesterUsageHeimdallMissedBlockProposal"

var _ObservableTopic_index = [...]uint16{0, 15, 25, 38, 51, 73, 85, 96, 112, 122, 142, 152, 167, 180, 192, 201, 216, 223, 237, 258, 267, 291, 302, 318, 330, 346, 351, 364, 381, 393, 397, 409, 423, 434, 440, 455, 465, 480, 492, 507, 519, 529, 541, 554, 572, 587, 597, 611, 638}

func (i ObservableTopic) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ObservableTopic_index)-1 {
		return "ObservableTopic(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ObservableTopic_name[_ObservableTopic_index[idx]:_ObservableTopic_index[idx+1]]
}
