// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/network.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UsageSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The total amount of gas (reserved + on-demand).
	TotalGas string `protobuf:"bytes,1,opt,name=total_gas,json=totalGas,proto3" json:"total_gas,omitempty"`
	// The total amount of reserved gas.
	ReservedGas string `protobuf:"bytes,2,opt,name=reserved_gas,json=reservedGas,proto3" json:"reserved_gas,omitempty"`
	// The total amount of on-demand gas.
	OnDemandGas   string `protobuf:"bytes,3,opt,name=on_demand_gas,json=onDemandGas,proto3" json:"on_demand_gas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageSummary) Reset() {
	*x = UsageSummary{}
	mi := &file_proto_network_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageSummary) ProtoMessage() {}

func (x *UsageSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageSummary.ProtoReflect.Descriptor instead.
func (*UsageSummary) Descriptor() ([]byte, []int) {
	return file_proto_network_proto_rawDescGZIP(), []int{0}
}

func (x *UsageSummary) GetTotalGas() string {
	if x != nil {
		return x.TotalGas
	}
	return ""
}

func (x *UsageSummary) GetReservedGas() string {
	if x != nil {
		return x.ReservedGas
	}
	return ""
}

func (x *UsageSummary) GetOnDemandGas() string {
	if x != nil {
		return x.OnDemandGas
	}
	return ""
}

type RequesterUsageSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The hour boundary as an ISO timestamp string (e.g., 2024-01-15T14:00:00Z).
	Hour string `protobuf:"bytes,1,opt,name=hour,proto3" json:"hour,omitempty"`
	// The usage summary associated with this requester.
	UsageSummary  *UsageSummary `protobuf:"bytes,2,opt,name=usage_summary,json=usageSummary,proto3" json:"usage_summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequesterUsageSummary) Reset() {
	*x = RequesterUsageSummary{}
	mi := &file_proto_network_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequesterUsageSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequesterUsageSummary) ProtoMessage() {}

func (x *RequesterUsageSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequesterUsageSummary.ProtoReflect.Descriptor instead.
func (*RequesterUsageSummary) Descriptor() ([]byte, []int) {
	return file_proto_network_proto_rawDescGZIP(), []int{1}
}

func (x *RequesterUsageSummary) GetHour() string {
	if x != nil {
		return x.Hour
	}
	return ""
}

func (x *RequesterUsageSummary) GetUsageSummary() *UsageSummary {
	if x != nil {
		return x.UsageSummary
	}
	return nil
}

type GetRequesterUsageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ISO timestamp string of the usage start time (e.g., 2024-01-15T14:00:00Z).
	StartTime string `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// The ISO timestamp string of the usage end time (e.g., 2024-01-15T17:00:00Z).
	EndTime string `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// The hex string of the requester to get the usage for (e.g., 0x...12).
	Requester     string `protobuf:"bytes,3,opt,name=requester,proto3" json:"requester,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequesterUsageRequest) Reset() {
	*x = GetRequesterUsageRequest{}
	mi := &file_proto_network_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequesterUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequesterUsageRequest) ProtoMessage() {}

func (x *GetRequesterUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequesterUsageRequest.ProtoReflect.Descriptor instead.
func (*GetRequesterUsageRequest) Descriptor() ([]byte, []int) {
	return file_proto_network_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequesterUsageRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *GetRequesterUsageRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *GetRequesterUsageRequest) GetRequester() string {
	if x != nil {
		return x.Requester
	}
	return ""
}

type GetRequesterUsageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list summarizing usage by month and clusters for the specified payer.
	UsageSummary  []*RequesterUsageSummary `protobuf:"bytes,1,rep,name=usage_summary,json=usageSummary,proto3" json:"usage_summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequesterUsageResponse) Reset() {
	*x = GetRequesterUsageResponse{}
	mi := &file_proto_network_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequesterUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequesterUsageResponse) ProtoMessage() {}

func (x *GetRequesterUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequesterUsageResponse.ProtoReflect.Descriptor instead.
func (*GetRequesterUsageResponse) Descriptor() ([]byte, []int) {
	return file_proto_network_proto_rawDescGZIP(), []int{3}
}

func (x *GetRequesterUsageResponse) GetUsageSummary() []*RequesterUsageSummary {
	if x != nil {
		return x.UsageSummary
	}
	return nil
}

var File_proto_network_proto protoreflect.FileDescriptor

const file_proto_network_proto_rawDesc = "" +
	"\n" +
	"\x13proto/network.proto\x12\anetwork\"r\n" +
	"\fUsageSummary\x12\x1b\n" +
	"\ttotal_gas\x18\x01 \x01(\tR\btotalGas\x12!\n" +
	"\freserved_gas\x18\x02 \x01(\tR\vreservedGas\x12\"\n" +
	"\ron_demand_gas\x18\x03 \x01(\tR\vonDemandGas\"g\n" +
	"\x15RequesterUsageSummary\x12\x12\n" +
	"\x04hour\x18\x01 \x01(\tR\x04hour\x12:\n" +
	"\rusage_summary\x18\x02 \x01(\v2\x15.network.UsageSummaryR\fusageSummary\"r\n" +
	"\x18GetRequesterUsageRequest\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\tR\aendTime\x12\x1c\n" +
	"\trequester\x18\x03 \x01(\tR\trequester\"`\n" +
	"\x19GetRequesterUsageResponse\x12C\n" +
	"\rusage_summary\x18\x01 \x03(\v2\x1e.network.RequesterUsageSummaryR\fusageSummary2m\n" +
	"\rProverNetwork\x12\\\n" +
	"\x11GetRequesterUsage\x12!.network.GetRequesterUsageRequest\x1a\".network.GetRequesterUsageResponse\"\x00b\x06proto3"

var (
	file_proto_network_proto_rawDescOnce sync.Once
	file_proto_network_proto_rawDescData []byte
)

func file_proto_network_proto_rawDescGZIP() []byte {
	file_proto_network_proto_rawDescOnce.Do(func() {
		file_proto_network_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_network_proto_rawDesc), len(file_proto_network_proto_rawDesc)))
	})
	return file_proto_network_proto_rawDescData
}

var file_proto_network_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_network_proto_goTypes = []any{
	(*UsageSummary)(nil),              // 0: network.UsageSummary
	(*RequesterUsageSummary)(nil),     // 1: network.RequesterUsageSummary
	(*GetRequesterUsageRequest)(nil),  // 2: network.GetRequesterUsageRequest
	(*GetRequesterUsageResponse)(nil), // 3: network.GetRequesterUsageResponse
}
var file_proto_network_proto_depIdxs = []int32{
	0, // 0: network.RequesterUsageSummary.usage_summary:type_name -> network.UsageSummary
	1, // 1: network.GetRequesterUsageResponse.usage_summary:type_name -> network.RequesterUsageSummary
	2, // 2: network.ProverNetwork.GetRequesterUsage:input_type -> network.GetRequesterUsageRequest
	3, // 3: network.ProverNetwork.GetRequesterUsage:output_type -> network.GetRequesterUsageResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_network_proto_init() }
func file_proto_network_proto_init() {
	if File_proto_network_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_network_proto_rawDesc), len(file_proto_network_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_network_proto_goTypes,
		DependencyIndexes: file_proto_network_proto_depIdxs,
		MessageInfos:      file_proto_network_proto_msgTypes,
	}.Build()
	File_proto_network_proto = out.File
	file_proto_network_proto_goTypes = nil
	file_proto_network_proto_depIdxs = nil
}
