// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: network.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_network_proto protoreflect.FileDescriptor

const file_network_proto_rawDesc = "" +
	"\n" +
	"\rnetwork.proto\x12\anetwork\x1a\vtypes.proto2\xf2N\n" +
	"\rProverNetwork\x12I\n" +
	"\fRequestProof\x12\x1a.types.RequestProofRequest\x1a\x1b.types.RequestProofResponse\"\x00\x12I\n" +
	"\fFulfillProof\x12\x1a.types.FulfillProofRequest\x1a\x1b.types.FulfillProofResponse\"\x00\x12I\n" +
	"\fExecuteProof\x12\x1a.types.ExecuteProofRequest\x1a\x1b.types.ExecuteProofResponse\"\x00\x12R\n" +
	"\x0fFailFulfillment\x12\x1d.types.FailFulfillmentRequest\x1a\x1e.types.FailFulfillmentResponse\"\x00\x12d\n" +
	"\x15GetProofRequestStatus\x12#.types.GetProofRequestStatusRequest\x1a$.types.GetProofRequestStatusResponse\"\x00\x12g\n" +
	"\x16GetProofRequestDetails\x12$.types.GetProofRequestDetailsRequest\x1a%.types.GetProofRequestDetailsResponse\"\x00\x12m\n" +
	"\x18GetFilteredProofRequests\x12&.types.GetFilteredProofRequestsRequest\x1a'.types.GetFilteredProofRequestsResponse\"\x00\x12Y\n" +
	"\x16SubscribeProofRequests\x12&.types.GetFilteredProofRequestsRequest\x1a\x13.types.ProofRequest\"\x000\x01\x12U\n" +
	"\x10GetSearchResults\x12\x1e.types.GetSearchResultsRequest\x1a\x1f.types.GetSearchResultsResponse\"\x00\x12g\n" +
	"\x16GetProofRequestMetrics\x12$.types.GetProofRequestMetricsRequest\x1a%.types.GetProofRequestMetricsResponse\"\x00\x12a\n" +
	"\x14GetProofRequestGraph\x12\".types.GetProofRequestGraphRequest\x1a#.types.GetProofRequestGraphResponse\"\x00\x12[\n" +
	"\x12GetAnalyticsGraphs\x12 .types.GetAnalyticsGraphsRequest\x1a!.types.GetAnalyticsGraphsResponse\"\x00\x12X\n" +
	"\x11GetOverviewGraphs\x12\x1f.types.GetOverviewGraphsRequest\x1a .types.GetOverviewGraphsResponse\"\x00\x12d\n" +
	"\x15GetProofRequestParams\x12#.types.GetProofRequestParamsRequest\x1a$.types.GetProofRequestParamsResponse\"\x00\x12=\n" +
	"\bGetNonce\x12\x16.types.GetNonceRequest\x1a\x17.types.GetNonceResponse\"\x00\x12O\n" +
	"\x0eSetAccountName\x12\x1c.types.SetAccountNameRequest\x1a\x1d.types.SetAccountNameResponse\"\x00\x12O\n" +
	"\x0eGetAccountName\x12\x1c.types.GetAccountNameRequest\x1a\x1d.types.GetAccountNameResponse\"\x00\x12X\n" +
	"\x11GetTermsSignature\x12\x1f.types.GetTermsSignatureRequest\x1a .types.GetTermsSignatureResponse\"\x00\x12X\n" +
	"\x11SetTermsSignature\x12\x1f.types.SetTermsSignatureRequest\x1a .types.SetTermsSignatureResponse\"\x00\x12C\n" +
	"\n" +
	"GetAccount\x12\x18.types.GetAccountRequest\x1a\x19.types.GetAccountResponse\"\x00\x12=\n" +
	"\bGetOwner\x12\x16.types.GetOwnerRequest\x1a\x17.types.GetOwnerResponse\"\x00\x12C\n" +
	"\n" +
	"GetProgram\x12\x18.types.GetProgramRequest\x1a\x19.types.GetProgramResponse\"\x00\x12L\n" +
	"\rCreateProgram\x12\x1b.types.CreateProgramRequest\x1a\x1c.types.CreateProgramResponse\"\x00\x12O\n" +
	"\x0eSetProgramName\x12\x1c.types.SetProgramNameRequest\x1a\x1d.types.SetProgramNameResponse\"\x00\x12C\n" +
	"\n" +
	"GetBalance\x12\x18.types.GetBalanceRequest\x1a\x19.types.GetBalanceResponse\"\x00\x12g\n" +
	"\x16GetFilteredBalanceLogs\x12$.types.GetFilteredBalanceLogsRequest\x1a%.types.GetFilteredBalanceLogsResponse\"\x00\x12@\n" +
	"\tAddCredit\x12\x17.types.AddCreditRequest\x1a\x18.types.AddCreditResponse\"\x00\x12a\n" +
	"\x14GetLatestBridgeBlock\x12\".types.GetLatestBridgeBlockRequest\x1a#.types.GetLatestBridgeBlockResponse\"\x00\x12^\n" +
	"\x13GetGasPriceEstimate\x12!.types.GetGasPriceEstimateRequest\x1a\".types.GetGasPriceEstimateResponse\"\x00\x12d\n" +
	"\x15GetTransactionDetails\x12#.types.GetTransactionDetailsRequest\x1a$.types.GetTransactionDetailsResponse\"\x00\x12X\n" +
	"\x11AddReservedCharge\x12\x1f.types.AddReservedChargeRequest\x1a .types.AddReservedChargeResponse\"\x00\x12X\n" +
	"\x11GetBillingSummary\x12\x1f.types.GetBillingSummaryRequest\x1a .types.GetBillingSummaryResponse\"\x00\x12F\n" +
	"\vUpdatePrice\x12\x19.types.UpdatePriceRequest\x1a\x1a.types.UpdatePriceResponse\"\x00\x12^\n" +
	"\x13GetFilteredClusters\x12!.types.GetFilteredClustersRequest\x1a\".types.GetFilteredClustersResponse\"\x00\x12R\n" +
	"\x0fGetUsageSummary\x12\x1d.types.GetUsageSummaryRequest\x1a\x1e.types.GetUsageSummaryResponse\"\x00\x12=\n" +
	"\bTransfer\x12\x16.types.TransferRequest\x1a\x17.types.TransferResponse\"\x00\x12X\n" +
	"\x11GetWithdrawParams\x12\x1f.types.GetWithdrawParamsRequest\x1a .types.GetWithdrawParamsResponse\"\x00\x12=\n" +
	"\bWithdraw\x12\x16.types.WithdrawRequest\x1a\x17.types.WithdrawResponse\"\x00\x12j\n" +
	"\x17GetFilteredReservations\x12%.types.GetFilteredReservationsRequest\x1a&.types.GetFilteredReservationsResponse\"\x00\x12O\n" +
	"\x0eAddReservation\x12\x1c.types.AddReservationRequest\x1a\x1d.types.AddReservationResponse\"\x00\x12X\n" +
	"\x11RemoveReservation\x12\x1f.types.RemoveReservationRequest\x1a .types.RemoveReservationResponse\"\x00\x12.\n" +
	"\x03Bid\x12\x11.types.BidRequest\x1a\x12.types.BidResponse\"\x00\x127\n" +
	"\x06Settle\x12\x14.types.SettleRequest\x1a\x15.types.SettleResponse\"\x00\x12[\n" +
	"\x12GetProversByUptime\x12 .types.GetProversByUptimeRequest\x1a!.types.GetProversByUptimeResponse\"\x00\x127\n" +
	"\x06SignIn\x12\x14.types.SignInRequest\x1a\x15.types.SignInResponse\"\x00\x12p\n" +
	"\x19GetOnboardedAccountsCount\x12'.types.GetOnboardedAccountsCountRequest\x1a(.types.GetOnboardedAccountsCountResponse\"\x00\x12y\n" +
	"\x1cGetFilteredOnboardedAccounts\x12*.types.GetFilteredOnboardedAccountsRequest\x1a+.types.GetFilteredOnboardedAccountsResponse\"\x00\x12O\n" +
	"\x0eGetLeaderboard\x12\x1c.types.GetLeaderboardRequest\x1a\x1d.types.GetLeaderboardResponse\"\x00\x12^\n" +
	"\x13GetLeaderboardStats\x12!.types.GetLeaderboardStatsRequest\x1a\".types.GetLeaderboardStatsResponse\"\x00\x12=\n" +
	"\bGetCodes\x12\x16.types.GetCodesRequest\x1a\x17.types.GetCodesResponse\"\x00\x12C\n" +
	"\n" +
	"RedeemCode\x12\x18.types.RedeemCodeRequest\x1a\x19.types.RedeemCodeResponse\"\x00\x12O\n" +
	"\x0eConnectTwitter\x12\x1c.types.ConnectTwitterRequest\x1a\x1d.types.ConnectTwitterResponse\"\x00\x12[\n" +
	"\x12CompleteOnboarding\x12 .types.CompleteOnboardingRequest\x1a!.types.CompleteOnboardingResponse\"\x00\x12^\n" +
	"\x13SetUseTwitterHandle\x12!.types.SetUseTwitterHandleRequest\x1a\".types.SetUseTwitterHandleResponse\"\x00\x12[\n" +
	"\x12SetUseTwitterImage\x12 .types.SetUseTwitterImageRequest\x1a!.types.SetUseTwitterImageResponse\"\x00\x12[\n" +
	"\x12RequestRandomProof\x12 .types.RequestRandomProofRequest\x1a!.types.RequestRandomProofResponse\"\x00\x12X\n" +
	"\x11SubmitCaptchaGame\x12\x1f.types.SubmitCaptchaGameRequest\x1a .types.SubmitCaptchaGameResponse\"\x00\x12F\n" +
	"\vRedeemStars\x12\x19.types.RedeemStarsRequest\x1a\x1a.types.RedeemStarsResponse\"\x00\x12a\n" +
	"\x14GetFlappyLeaderboard\x12\".types.GetFlappyLeaderboardRequest\x1a#.types.GetFlappyLeaderboardResponse\"\x00\x12X\n" +
	"\x11SetTurboHighScore\x12\x1f.types.SetTurboHighScoreRequest\x1a .types.SetTurboHighScoreResponse\"\x00\x12O\n" +
	"\x0eSubmitQuizGame\x12\x1c.types.SubmitQuizGameRequest\x1a\x1d.types.SubmitQuizGameResponse\"\x00\x12^\n" +
	"\x13GetTurboLeaderboard\x12!.types.GetTurboLeaderboardRequest\x1a\".types.GetTurboLeaderboardResponse\"\x00\x12g\n" +
	"\x16SubmitEthBlockMetadata\x12$.types.SubmitEthBlockMetadataRequest\x1a%.types.SubmitEthBlockMetadataResponse\"\x00\x12v\n" +
	"\x1bGetFilteredEthBlockRequests\x12).types.GetFilteredEthBlockRequestsRequest\x1a*.types.GetFilteredEthBlockRequestsResponse\"\x00\x12U\n" +
	"\x10Set2048HighScore\x12\x1e.types.Set2048HighScoreRequest\x1a\x1f.types.Set2048HighScoreResponse\"\x00\x12g\n" +
	"\x16SetVolleyballHighScore\x12$.types.SetVolleyballHighScoreRequest\x1a%.types.SetVolleyballHighScoreResponse\"\x00\x12p\n" +
	"\x19GetEthBlockRequestMetrics\x12'.types.GetEthBlockRequestMetricsRequest\x1a(.types.GetEthBlockRequestMetricsResponse\"\x00\x12s\n" +
	"\x1aSetTurboTimeTrialHighScore\x12(.types.SetTurboTimeTrialHighScoreRequest\x1a).types.SetTurboTimeTrialHighScoreResponse\"\x00\x12d\n" +
	"\x15SetCoinCrazeHighScore\x12#.types.SetCoinCrazeHighScoreRequest\x1a$.types.SetCoinCrazeHighScoreResponse\"\x00\x12U\n" +
	"\x10SetLeanHighScore\x12\x1e.types.SetLeanHighScoreRequest\x1a\x1f.types.SetLeanHighScoreResponse\"\x00\x12U\n" +
	"\x10SetFlowHighScore\x12\x1e.types.SetFlowHighScoreRequest\x1a\x1f.types.SetFlowHighScoreResponse\"\x00\x12[\n" +
	"\x12SetRollupHighScore\x12 .types.SetRollupHighScoreRequest\x1a!.types.SetRollupHighScoreResponse\"\x00\x12R\n" +
	"\x0fGetPendingStars\x12\x1d.types.GetPendingStarsRequest\x1a\x1e.types.GetPendingStarsResponse\"\x00\x12[\n" +
	"\x12GetWhitelistStatus\x12 .types.GetWhitelistStatusRequest\x1a!.types.GetWhitelistStatusResponse\"\x00\x12=\n" +
	"\bClaimGpu\x12\x16.types.ClaimGpuRequest\x1a\x17.types.ClaimGpuResponse\"\x00\x12L\n" +
	"\rSetGpuVariant\x12\x1b.types.SetGpuVariantRequest\x1a\x1c.types.SetGpuVariantResponse\"\x00\x12g\n" +
	"\x16LinkWhitelistedTwitter\x12$.types.LinkWhitelistedTwitterRequest\x1a%.types.LinkWhitelistedTwitterResponse\"\x00\x12[\n" +
	"\x12RetrieveProvingKey\x12 .types.RetrieveProvingKeyRequest\x1a!.types.RetrieveProvingKeyResponse\"\x00\x12d\n" +
	"\x15LinkWhitelistedGithub\x12#.types.LinkWhitelistedGithubRequest\x1a$.types.LinkWhitelistedGithubResponse\"\x00\x12g\n" +
	"\x16LinkWhitelistedDiscord\x12$.types.LinkWhitelistedDiscordRequest\x1a%.types.LinkWhitelistedDiscordResponse\"\x00\x12a\n" +
	"\x14GetProverLeaderboard\x12\".types.GetProverLeaderboardRequest\x1a#.types.GetProverLeaderboardResponse\"\x00\x12R\n" +
	"\x0fGetFilteredGpus\x12\x1d.types.GetFilteredGpusRequest\x1a\x1e.types.GetFilteredGpusResponse\"\x00\x12X\n" +
	"\x11SetGpuCoordinates\x12\x1f.types.SetGpuCoordinatesRequest\x1a .types.SetGpuCoordinatesResponse\"\x00\x12@\n" +
	"\tGetPoints\x12\x17.types.GetPointsRequest\x1a\x18.types.GetPointsResponse\"\x00\x12L\n" +
	"\rProcessClicks\x12\x1b.types.ProcessClicksRequest\x1a\x1c.types.ProcessClicksResponse\"\x00\x12R\n" +
	"\x0fPurchaseUpgrade\x12\x1d.types.PurchaseUpgradeRequest\x1a\x1e.types.PurchaseUpgradeResponse\"\x00\x12.\n" +
	"\x03Bet\x12\x11.types.BetRequest\x1a\x12.types.BetResponse\"\x00\x12X\n" +
	"\x11GetContestDetails\x12\x1f.types.GetContestDetailsRequest\x1a .types.GetContestDetailsResponse\"\x00\x12U\n" +
	"\x10GetLatestContest\x12\x1e.types.GetLatestContestRequest\x1a\x1f.types.GetLatestContestResponse\"\x00\x12X\n" +
	"\x11GetContestBettors\x12\x1f.types.GetContestBettorsRequest\x1a .types.GetContestBettorsResponse\"\x00\x12L\n" +
	"\rGetGpuMetrics\x12\x1b.types.GetGpuMetricsRequest\x1a\x1c.types.GetGpuMetricsResponse\"\x00\x12p\n" +
	"\x19GetFilteredProverActivity\x12'.types.GetFilteredProverActivityRequest\x1a(.types.GetFilteredProverActivityResponse\"\x00\x12U\n" +
	"\x10GetProverMetrics\x12\x1e.types.GetProverMetricsRequest\x1a\x1f.types.GetProverMetricsResponse\"\x00\x12d\n" +
	"\x15GetFilteredBetHistory\x12#.types.GetFilteredBetHistoryRequest\x1a$.types.GetFilteredBetHistoryResponse\"\x00\x12R\n" +
	"\x0fGetGpuTeamStats\x12\x1d.types.GetGpuTeamStatsRequest\x1a\x1e.types.GetGpuTeamStatsResponse\"\x00\x12R\n" +
	"\x0fGetConfigValues\x12\x1d.types.GetConfigValuesRequest\x1a\x1e.types.GetConfigValuesResponse\"\x00\x12O\n" +
	"\x0eGetProverStats\x12\x1c.types.GetProverStatsRequest\x1a\x1d.types.GetProverStatsResponse\"\x00\x12g\n" +
	"\x16GetFilteredProverStats\x12$.types.GetFilteredProverStatsRequest\x1a%.types.GetFilteredProverStatsResponse\"\x00\x12a\n" +
	"\x14GetProverStatsDetail\x12\".types.GetProverStatsDetailRequest\x1a#.types.GetProverStatsDetailResponse\"\x00\x12g\n" +
	"\x16GetProverSearchResults\x12$.types.GetProverSearchResultsRequest\x1a%.types.GetProverSearchResultsResponse\"\x00\x12d\n" +
	"\x15GetFilteredBidHistory\x12#.types.GetFilteredBidHistoryRequest\x1a$.types.GetFilteredBidHistoryResponse\"\x00\x12d\n" +
	"\x15GetTEEWhitelistStatus\x12#.types.GetTEEWhitelistStatusRequest\x1a$.types.GetTEEWhitelistStatusResponse\"\x00\x12a\n" +
	"\x14GetSettlementRequest\x12\".types.GetSettlementRequestRequest\x1a#.types.GetSettlementRequestResponse\"\x00\x12|\n" +
	"\x1dGetFilteredSettlementRequests\x12+.types.GetFilteredSettlementRequestsRequest\x1a,.types.GetFilteredSettlementRequestsResponse\"\x00\x12[\n" +
	"\x12GetFilteredProvers\x12 .types.GetFilteredProversRequest\x1a!.types.GetFilteredProversResponse\"\x00\x12d\n" +
	"\x15GetProverStakeBalance\x12#.types.GetProverStakeBalanceRequest\x1a$.types.GetProverStakeBalanceResponse\"\x00\x12\x88\x01\n" +
	"!GetFilteredStakerStakeBalanceLogs\x12/.types.GetFilteredStakerStakeBalanceLogsRequest\x1a0.types.GetFilteredStakerStakeBalanceLogsResponse\"\x00\x12\x88\x01\n" +
	"!GetFilteredProverStakeBalanceLogs\x12/.types.GetFilteredProverStakeBalanceLogsRequest\x1a0.types.GetFilteredProverStakeBalanceLogsResponse\"\x00\x12^\n" +
	"\x13GetDelegationParams\x12!.types.GetDelegationParamsRequest\x1a\".types.GetDelegationParamsResponse\"\x00\x12L\n" +
	"\rSetDelegation\x12\x1b.types.SetDelegationRequest\x1a\x1c.types.SetDelegationResponse\"\x00\x12L\n" +
	"\rGetDelegation\x12\x1b.types.GetDelegationRequest\x1a\x1c.types.GetDelegationResponse\"\x00\x12|\n" +
	"\x1dGetFilteredWithdrawalReceipts\x12+.types.GetFilteredWithdrawalReceiptsRequest\x1a,.types.GetFilteredWithdrawalReceiptsResponse\"\x00b\x06proto3"

var file_network_proto_goTypes = []any{
	(*RequestProofRequest)(nil),                       // 0: types.RequestProofRequest
	(*FulfillProofRequest)(nil),                       // 1: types.FulfillProofRequest
	(*ExecuteProofRequest)(nil),                       // 2: types.ExecuteProofRequest
	(*FailFulfillmentRequest)(nil),                    // 3: types.FailFulfillmentRequest
	(*GetProofRequestStatusRequest)(nil),              // 4: types.GetProofRequestStatusRequest
	(*GetProofRequestDetailsRequest)(nil),             // 5: types.GetProofRequestDetailsRequest
	(*GetFilteredProofRequestsRequest)(nil),           // 6: types.GetFilteredProofRequestsRequest
	(*GetSearchResultsRequest)(nil),                   // 7: types.GetSearchResultsRequest
	(*GetProofRequestMetricsRequest)(nil),             // 8: types.GetProofRequestMetricsRequest
	(*GetProofRequestGraphRequest)(nil),               // 9: types.GetProofRequestGraphRequest
	(*GetAnalyticsGraphsRequest)(nil),                 // 10: types.GetAnalyticsGraphsRequest
	(*GetOverviewGraphsRequest)(nil),                  // 11: types.GetOverviewGraphsRequest
	(*GetProofRequestParamsRequest)(nil),              // 12: types.GetProofRequestParamsRequest
	(*GetNonceRequest)(nil),                           // 13: types.GetNonceRequest
	(*SetAccountNameRequest)(nil),                     // 14: types.SetAccountNameRequest
	(*GetAccountNameRequest)(nil),                     // 15: types.GetAccountNameRequest
	(*GetTermsSignatureRequest)(nil),                  // 16: types.GetTermsSignatureRequest
	(*SetTermsSignatureRequest)(nil),                  // 17: types.SetTermsSignatureRequest
	(*GetAccountRequest)(nil),                         // 18: types.GetAccountRequest
	(*GetOwnerRequest)(nil),                           // 19: types.GetOwnerRequest
	(*GetProgramRequest)(nil),                         // 20: types.GetProgramRequest
	(*CreateProgramRequest)(nil),                      // 21: types.CreateProgramRequest
	(*SetProgramNameRequest)(nil),                     // 22: types.SetProgramNameRequest
	(*GetBalanceRequest)(nil),                         // 23: types.GetBalanceRequest
	(*GetFilteredBalanceLogsRequest)(nil),             // 24: types.GetFilteredBalanceLogsRequest
	(*AddCreditRequest)(nil),                          // 25: types.AddCreditRequest
	(*GetLatestBridgeBlockRequest)(nil),               // 26: types.GetLatestBridgeBlockRequest
	(*GetGasPriceEstimateRequest)(nil),                // 27: types.GetGasPriceEstimateRequest
	(*GetTransactionDetailsRequest)(nil),              // 28: types.GetTransactionDetailsRequest
	(*AddReservedChargeRequest)(nil),                  // 29: types.AddReservedChargeRequest
	(*GetBillingSummaryRequest)(nil),                  // 30: types.GetBillingSummaryRequest
	(*UpdatePriceRequest)(nil),                        // 31: types.UpdatePriceRequest
	(*GetFilteredClustersRequest)(nil),                // 32: types.GetFilteredClustersRequest
	(*GetUsageSummaryRequest)(nil),                    // 33: types.GetUsageSummaryRequest
	(*TransferRequest)(nil),                           // 34: types.TransferRequest
	(*GetWithdrawParamsRequest)(nil),                  // 35: types.GetWithdrawParamsRequest
	(*WithdrawRequest)(nil),                           // 36: types.WithdrawRequest
	(*GetFilteredReservationsRequest)(nil),            // 37: types.GetFilteredReservationsRequest
	(*AddReservationRequest)(nil),                     // 38: types.AddReservationRequest
	(*RemoveReservationRequest)(nil),                  // 39: types.RemoveReservationRequest
	(*BidRequest)(nil),                                // 40: types.BidRequest
	(*SettleRequest)(nil),                             // 41: types.SettleRequest
	(*GetProversByUptimeRequest)(nil),                 // 42: types.GetProversByUptimeRequest
	(*SignInRequest)(nil),                             // 43: types.SignInRequest
	(*GetOnboardedAccountsCountRequest)(nil),          // 44: types.GetOnboardedAccountsCountRequest
	(*GetFilteredOnboardedAccountsRequest)(nil),       // 45: types.GetFilteredOnboardedAccountsRequest
	(*GetLeaderboardRequest)(nil),                     // 46: types.GetLeaderboardRequest
	(*GetLeaderboardStatsRequest)(nil),                // 47: types.GetLeaderboardStatsRequest
	(*GetCodesRequest)(nil),                           // 48: types.GetCodesRequest
	(*RedeemCodeRequest)(nil),                         // 49: types.RedeemCodeRequest
	(*ConnectTwitterRequest)(nil),                     // 50: types.ConnectTwitterRequest
	(*CompleteOnboardingRequest)(nil),                 // 51: types.CompleteOnboardingRequest
	(*SetUseTwitterHandleRequest)(nil),                // 52: types.SetUseTwitterHandleRequest
	(*SetUseTwitterImageRequest)(nil),                 // 53: types.SetUseTwitterImageRequest
	(*RequestRandomProofRequest)(nil),                 // 54: types.RequestRandomProofRequest
	(*SubmitCaptchaGameRequest)(nil),                  // 55: types.SubmitCaptchaGameRequest
	(*RedeemStarsRequest)(nil),                        // 56: types.RedeemStarsRequest
	(*GetFlappyLeaderboardRequest)(nil),               // 57: types.GetFlappyLeaderboardRequest
	(*SetTurboHighScoreRequest)(nil),                  // 58: types.SetTurboHighScoreRequest
	(*SubmitQuizGameRequest)(nil),                     // 59: types.SubmitQuizGameRequest
	(*GetTurboLeaderboardRequest)(nil),                // 60: types.GetTurboLeaderboardRequest
	(*SubmitEthBlockMetadataRequest)(nil),             // 61: types.SubmitEthBlockMetadataRequest
	(*GetFilteredEthBlockRequestsRequest)(nil),        // 62: types.GetFilteredEthBlockRequestsRequest
	(*Set2048HighScoreRequest)(nil),                   // 63: types.Set2048HighScoreRequest
	(*SetVolleyballHighScoreRequest)(nil),             // 64: types.SetVolleyballHighScoreRequest
	(*GetEthBlockRequestMetricsRequest)(nil),          // 65: types.GetEthBlockRequestMetricsRequest
	(*SetTurboTimeTrialHighScoreRequest)(nil),         // 66: types.SetTurboTimeTrialHighScoreRequest
	(*SetCoinCrazeHighScoreRequest)(nil),              // 67: types.SetCoinCrazeHighScoreRequest
	(*SetLeanHighScoreRequest)(nil),                   // 68: types.SetLeanHighScoreRequest
	(*SetFlowHighScoreRequest)(nil),                   // 69: types.SetFlowHighScoreRequest
	(*SetRollupHighScoreRequest)(nil),                 // 70: types.SetRollupHighScoreRequest
	(*GetPendingStarsRequest)(nil),                    // 71: types.GetPendingStarsRequest
	(*GetWhitelistStatusRequest)(nil),                 // 72: types.GetWhitelistStatusRequest
	(*ClaimGpuRequest)(nil),                           // 73: types.ClaimGpuRequest
	(*SetGpuVariantRequest)(nil),                      // 74: types.SetGpuVariantRequest
	(*LinkWhitelistedTwitterRequest)(nil),             // 75: types.LinkWhitelistedTwitterRequest
	(*RetrieveProvingKeyRequest)(nil),                 // 76: types.RetrieveProvingKeyRequest
	(*LinkWhitelistedGithubRequest)(nil),              // 77: types.LinkWhitelistedGithubRequest
	(*LinkWhitelistedDiscordRequest)(nil),             // 78: types.LinkWhitelistedDiscordRequest
	(*GetProverLeaderboardRequest)(nil),               // 79: types.GetProverLeaderboardRequest
	(*GetFilteredGpusRequest)(nil),                    // 80: types.GetFilteredGpusRequest
	(*SetGpuCoordinatesRequest)(nil),                  // 81: types.SetGpuCoordinatesRequest
	(*GetPointsRequest)(nil),                          // 82: types.GetPointsRequest
	(*ProcessClicksRequest)(nil),                      // 83: types.ProcessClicksRequest
	(*PurchaseUpgradeRequest)(nil),                    // 84: types.PurchaseUpgradeRequest
	(*BetRequest)(nil),                                // 85: types.BetRequest
	(*GetContestDetailsRequest)(nil),                  // 86: types.GetContestDetailsRequest
	(*GetLatestContestRequest)(nil),                   // 87: types.GetLatestContestRequest
	(*GetContestBettorsRequest)(nil),                  // 88: types.GetContestBettorsRequest
	(*GetGpuMetricsRequest)(nil),                      // 89: types.GetGpuMetricsRequest
	(*GetFilteredProverActivityRequest)(nil),          // 90: types.GetFilteredProverActivityRequest
	(*GetProverMetricsRequest)(nil),                   // 91: types.GetProverMetricsRequest
	(*GetFilteredBetHistoryRequest)(nil),              // 92: types.GetFilteredBetHistoryRequest
	(*GetGpuTeamStatsRequest)(nil),                    // 93: types.GetGpuTeamStatsRequest
	(*GetConfigValuesRequest)(nil),                    // 94: types.GetConfigValuesRequest
	(*GetProverStatsRequest)(nil),                     // 95: types.GetProverStatsRequest
	(*GetFilteredProverStatsRequest)(nil),             // 96: types.GetFilteredProverStatsRequest
	(*GetProverStatsDetailRequest)(nil),               // 97: types.GetProverStatsDetailRequest
	(*GetProverSearchResultsRequest)(nil),             // 98: types.GetProverSearchResultsRequest
	(*GetFilteredBidHistoryRequest)(nil),              // 99: types.GetFilteredBidHistoryRequest
	(*GetTEEWhitelistStatusRequest)(nil),              // 100: types.GetTEEWhitelistStatusRequest
	(*GetSettlementRequestRequest)(nil),               // 101: types.GetSettlementRequestRequest
	(*GetFilteredSettlementRequestsRequest)(nil),      // 102: types.GetFilteredSettlementRequestsRequest
	(*GetFilteredProversRequest)(nil),                 // 103: types.GetFilteredProversRequest
	(*GetProverStakeBalanceRequest)(nil),              // 104: types.GetProverStakeBalanceRequest
	(*GetFilteredStakerStakeBalanceLogsRequest)(nil),  // 105: types.GetFilteredStakerStakeBalanceLogsRequest
	(*GetFilteredProverStakeBalanceLogsRequest)(nil),  // 106: types.GetFilteredProverStakeBalanceLogsRequest
	(*GetDelegationParamsRequest)(nil),                // 107: types.GetDelegationParamsRequest
	(*SetDelegationRequest)(nil),                      // 108: types.SetDelegationRequest
	(*GetDelegationRequest)(nil),                      // 109: types.GetDelegationRequest
	(*GetFilteredWithdrawalReceiptsRequest)(nil),      // 110: types.GetFilteredWithdrawalReceiptsRequest
	(*RequestProofResponse)(nil),                      // 111: types.RequestProofResponse
	(*FulfillProofResponse)(nil),                      // 112: types.FulfillProofResponse
	(*ExecuteProofResponse)(nil),                      // 113: types.ExecuteProofResponse
	(*FailFulfillmentResponse)(nil),                   // 114: types.FailFulfillmentResponse
	(*GetProofRequestStatusResponse)(nil),             // 115: types.GetProofRequestStatusResponse
	(*GetProofRequestDetailsResponse)(nil),            // 116: types.GetProofRequestDetailsResponse
	(*GetFilteredProofRequestsResponse)(nil),          // 117: types.GetFilteredProofRequestsResponse
	(*ProofRequest)(nil),                              // 118: types.ProofRequest
	(*GetSearchResultsResponse)(nil),                  // 119: types.GetSearchResultsResponse
	(*GetProofRequestMetricsResponse)(nil),            // 120: types.GetProofRequestMetricsResponse
	(*GetProofRequestGraphResponse)(nil),              // 121: types.GetProofRequestGraphResponse
	(*GetAnalyticsGraphsResponse)(nil),                // 122: types.GetAnalyticsGraphsResponse
	(*GetOverviewGraphsResponse)(nil),                 // 123: types.GetOverviewGraphsResponse
	(*GetProofRequestParamsResponse)(nil),             // 124: types.GetProofRequestParamsResponse
	(*GetNonceResponse)(nil),                          // 125: types.GetNonceResponse
	(*SetAccountNameResponse)(nil),                    // 126: types.SetAccountNameResponse
	(*GetAccountNameResponse)(nil),                    // 127: types.GetAccountNameResponse
	(*GetTermsSignatureResponse)(nil),                 // 128: types.GetTermsSignatureResponse
	(*SetTermsSignatureResponse)(nil),                 // 129: types.SetTermsSignatureResponse
	(*GetAccountResponse)(nil),                        // 130: types.GetAccountResponse
	(*GetOwnerResponse)(nil),                          // 131: types.GetOwnerResponse
	(*GetProgramResponse)(nil),                        // 132: types.GetProgramResponse
	(*CreateProgramResponse)(nil),                     // 133: types.CreateProgramResponse
	(*SetProgramNameResponse)(nil),                    // 134: types.SetProgramNameResponse
	(*GetBalanceResponse)(nil),                        // 135: types.GetBalanceResponse
	(*GetFilteredBalanceLogsResponse)(nil),            // 136: types.GetFilteredBalanceLogsResponse
	(*AddCreditResponse)(nil),                         // 137: types.AddCreditResponse
	(*GetLatestBridgeBlockResponse)(nil),              // 138: types.GetLatestBridgeBlockResponse
	(*GetGasPriceEstimateResponse)(nil),               // 139: types.GetGasPriceEstimateResponse
	(*GetTransactionDetailsResponse)(nil),             // 140: types.GetTransactionDetailsResponse
	(*AddReservedChargeResponse)(nil),                 // 141: types.AddReservedChargeResponse
	(*GetBillingSummaryResponse)(nil),                 // 142: types.GetBillingSummaryResponse
	(*UpdatePriceResponse)(nil),                       // 143: types.UpdatePriceResponse
	(*GetFilteredClustersResponse)(nil),               // 144: types.GetFilteredClustersResponse
	(*GetUsageSummaryResponse)(nil),                   // 145: types.GetUsageSummaryResponse
	(*TransferResponse)(nil),                          // 146: types.TransferResponse
	(*GetWithdrawParamsResponse)(nil),                 // 147: types.GetWithdrawParamsResponse
	(*WithdrawResponse)(nil),                          // 148: types.WithdrawResponse
	(*GetFilteredReservationsResponse)(nil),           // 149: types.GetFilteredReservationsResponse
	(*AddReservationResponse)(nil),                    // 150: types.AddReservationResponse
	(*RemoveReservationResponse)(nil),                 // 151: types.RemoveReservationResponse
	(*BidResponse)(nil),                               // 152: types.BidResponse
	(*SettleResponse)(nil),                            // 153: types.SettleResponse
	(*GetProversByUptimeResponse)(nil),                // 154: types.GetProversByUptimeResponse
	(*SignInResponse)(nil),                            // 155: types.SignInResponse
	(*GetOnboardedAccountsCountResponse)(nil),         // 156: types.GetOnboardedAccountsCountResponse
	(*GetFilteredOnboardedAccountsResponse)(nil),      // 157: types.GetFilteredOnboardedAccountsResponse
	(*GetLeaderboardResponse)(nil),                    // 158: types.GetLeaderboardResponse
	(*GetLeaderboardStatsResponse)(nil),               // 159: types.GetLeaderboardStatsResponse
	(*GetCodesResponse)(nil),                          // 160: types.GetCodesResponse
	(*RedeemCodeResponse)(nil),                        // 161: types.RedeemCodeResponse
	(*ConnectTwitterResponse)(nil),                    // 162: types.ConnectTwitterResponse
	(*CompleteOnboardingResponse)(nil),                // 163: types.CompleteOnboardingResponse
	(*SetUseTwitterHandleResponse)(nil),               // 164: types.SetUseTwitterHandleResponse
	(*SetUseTwitterImageResponse)(nil),                // 165: types.SetUseTwitterImageResponse
	(*RequestRandomProofResponse)(nil),                // 166: types.RequestRandomProofResponse
	(*SubmitCaptchaGameResponse)(nil),                 // 167: types.SubmitCaptchaGameResponse
	(*RedeemStarsResponse)(nil),                       // 168: types.RedeemStarsResponse
	(*GetFlappyLeaderboardResponse)(nil),              // 169: types.GetFlappyLeaderboardResponse
	(*SetTurboHighScoreResponse)(nil),                 // 170: types.SetTurboHighScoreResponse
	(*SubmitQuizGameResponse)(nil),                    // 171: types.SubmitQuizGameResponse
	(*GetTurboLeaderboardResponse)(nil),               // 172: types.GetTurboLeaderboardResponse
	(*SubmitEthBlockMetadataResponse)(nil),            // 173: types.SubmitEthBlockMetadataResponse
	(*GetFilteredEthBlockRequestsResponse)(nil),       // 174: types.GetFilteredEthBlockRequestsResponse
	(*Set2048HighScoreResponse)(nil),                  // 175: types.Set2048HighScoreResponse
	(*SetVolleyballHighScoreResponse)(nil),            // 176: types.SetVolleyballHighScoreResponse
	(*GetEthBlockRequestMetricsResponse)(nil),         // 177: types.GetEthBlockRequestMetricsResponse
	(*SetTurboTimeTrialHighScoreResponse)(nil),        // 178: types.SetTurboTimeTrialHighScoreResponse
	(*SetCoinCrazeHighScoreResponse)(nil),             // 179: types.SetCoinCrazeHighScoreResponse
	(*SetLeanHighScoreResponse)(nil),                  // 180: types.SetLeanHighScoreResponse
	(*SetFlowHighScoreResponse)(nil),                  // 181: types.SetFlowHighScoreResponse
	(*SetRollupHighScoreResponse)(nil),                // 182: types.SetRollupHighScoreResponse
	(*GetPendingStarsResponse)(nil),                   // 183: types.GetPendingStarsResponse
	(*GetWhitelistStatusResponse)(nil),                // 184: types.GetWhitelistStatusResponse
	(*ClaimGpuResponse)(nil),                          // 185: types.ClaimGpuResponse
	(*SetGpuVariantResponse)(nil),                     // 186: types.SetGpuVariantResponse
	(*LinkWhitelistedTwitterResponse)(nil),            // 187: types.LinkWhitelistedTwitterResponse
	(*RetrieveProvingKeyResponse)(nil),                // 188: types.RetrieveProvingKeyResponse
	(*LinkWhitelistedGithubResponse)(nil),             // 189: types.LinkWhitelistedGithubResponse
	(*LinkWhitelistedDiscordResponse)(nil),            // 190: types.LinkWhitelistedDiscordResponse
	(*GetProverLeaderboardResponse)(nil),              // 191: types.GetProverLeaderboardResponse
	(*GetFilteredGpusResponse)(nil),                   // 192: types.GetFilteredGpusResponse
	(*SetGpuCoordinatesResponse)(nil),                 // 193: types.SetGpuCoordinatesResponse
	(*GetPointsResponse)(nil),                         // 194: types.GetPointsResponse
	(*ProcessClicksResponse)(nil),                     // 195: types.ProcessClicksResponse
	(*PurchaseUpgradeResponse)(nil),                   // 196: types.PurchaseUpgradeResponse
	(*BetResponse)(nil),                               // 197: types.BetResponse
	(*GetContestDetailsResponse)(nil),                 // 198: types.GetContestDetailsResponse
	(*GetLatestContestResponse)(nil),                  // 199: types.GetLatestContestResponse
	(*GetContestBettorsResponse)(nil),                 // 200: types.GetContestBettorsResponse
	(*GetGpuMetricsResponse)(nil),                     // 201: types.GetGpuMetricsResponse
	(*GetFilteredProverActivityResponse)(nil),         // 202: types.GetFilteredProverActivityResponse
	(*GetProverMetricsResponse)(nil),                  // 203: types.GetProverMetricsResponse
	(*GetFilteredBetHistoryResponse)(nil),             // 204: types.GetFilteredBetHistoryResponse
	(*GetGpuTeamStatsResponse)(nil),                   // 205: types.GetGpuTeamStatsResponse
	(*GetConfigValuesResponse)(nil),                   // 206: types.GetConfigValuesResponse
	(*GetProverStatsResponse)(nil),                    // 207: types.GetProverStatsResponse
	(*GetFilteredProverStatsResponse)(nil),            // 208: types.GetFilteredProverStatsResponse
	(*GetProverStatsDetailResponse)(nil),              // 209: types.GetProverStatsDetailResponse
	(*GetProverSearchResultsResponse)(nil),            // 210: types.GetProverSearchResultsResponse
	(*GetFilteredBidHistoryResponse)(nil),             // 211: types.GetFilteredBidHistoryResponse
	(*GetTEEWhitelistStatusResponse)(nil),             // 212: types.GetTEEWhitelistStatusResponse
	(*GetSettlementRequestResponse)(nil),              // 213: types.GetSettlementRequestResponse
	(*GetFilteredSettlementRequestsResponse)(nil),     // 214: types.GetFilteredSettlementRequestsResponse
	(*GetFilteredProversResponse)(nil),                // 215: types.GetFilteredProversResponse
	(*GetProverStakeBalanceResponse)(nil),             // 216: types.GetProverStakeBalanceResponse
	(*GetFilteredStakerStakeBalanceLogsResponse)(nil), // 217: types.GetFilteredStakerStakeBalanceLogsResponse
	(*GetFilteredProverStakeBalanceLogsResponse)(nil), // 218: types.GetFilteredProverStakeBalanceLogsResponse
	(*GetDelegationParamsResponse)(nil),               // 219: types.GetDelegationParamsResponse
	(*SetDelegationResponse)(nil),                     // 220: types.SetDelegationResponse
	(*GetDelegationResponse)(nil),                     // 221: types.GetDelegationResponse
	(*GetFilteredWithdrawalReceiptsResponse)(nil),     // 222: types.GetFilteredWithdrawalReceiptsResponse
}
var file_network_proto_depIdxs = []int32{
	0,   // 0: network.ProverNetwork.RequestProof:input_type -> types.RequestProofRequest
	1,   // 1: network.ProverNetwork.FulfillProof:input_type -> types.FulfillProofRequest
	2,   // 2: network.ProverNetwork.ExecuteProof:input_type -> types.ExecuteProofRequest
	3,   // 3: network.ProverNetwork.FailFulfillment:input_type -> types.FailFulfillmentRequest
	4,   // 4: network.ProverNetwork.GetProofRequestStatus:input_type -> types.GetProofRequestStatusRequest
	5,   // 5: network.ProverNetwork.GetProofRequestDetails:input_type -> types.GetProofRequestDetailsRequest
	6,   // 6: network.ProverNetwork.GetFilteredProofRequests:input_type -> types.GetFilteredProofRequestsRequest
	6,   // 7: network.ProverNetwork.SubscribeProofRequests:input_type -> types.GetFilteredProofRequestsRequest
	7,   // 8: network.ProverNetwork.GetSearchResults:input_type -> types.GetSearchResultsRequest
	8,   // 9: network.ProverNetwork.GetProofRequestMetrics:input_type -> types.GetProofRequestMetricsRequest
	9,   // 10: network.ProverNetwork.GetProofRequestGraph:input_type -> types.GetProofRequestGraphRequest
	10,  // 11: network.ProverNetwork.GetAnalyticsGraphs:input_type -> types.GetAnalyticsGraphsRequest
	11,  // 12: network.ProverNetwork.GetOverviewGraphs:input_type -> types.GetOverviewGraphsRequest
	12,  // 13: network.ProverNetwork.GetProofRequestParams:input_type -> types.GetProofRequestParamsRequest
	13,  // 14: network.ProverNetwork.GetNonce:input_type -> types.GetNonceRequest
	14,  // 15: network.ProverNetwork.SetAccountName:input_type -> types.SetAccountNameRequest
	15,  // 16: network.ProverNetwork.GetAccountName:input_type -> types.GetAccountNameRequest
	16,  // 17: network.ProverNetwork.GetTermsSignature:input_type -> types.GetTermsSignatureRequest
	17,  // 18: network.ProverNetwork.SetTermsSignature:input_type -> types.SetTermsSignatureRequest
	18,  // 19: network.ProverNetwork.GetAccount:input_type -> types.GetAccountRequest
	19,  // 20: network.ProverNetwork.GetOwner:input_type -> types.GetOwnerRequest
	20,  // 21: network.ProverNetwork.GetProgram:input_type -> types.GetProgramRequest
	21,  // 22: network.ProverNetwork.CreateProgram:input_type -> types.CreateProgramRequest
	22,  // 23: network.ProverNetwork.SetProgramName:input_type -> types.SetProgramNameRequest
	23,  // 24: network.ProverNetwork.GetBalance:input_type -> types.GetBalanceRequest
	24,  // 25: network.ProverNetwork.GetFilteredBalanceLogs:input_type -> types.GetFilteredBalanceLogsRequest
	25,  // 26: network.ProverNetwork.AddCredit:input_type -> types.AddCreditRequest
	26,  // 27: network.ProverNetwork.GetLatestBridgeBlock:input_type -> types.GetLatestBridgeBlockRequest
	27,  // 28: network.ProverNetwork.GetGasPriceEstimate:input_type -> types.GetGasPriceEstimateRequest
	28,  // 29: network.ProverNetwork.GetTransactionDetails:input_type -> types.GetTransactionDetailsRequest
	29,  // 30: network.ProverNetwork.AddReservedCharge:input_type -> types.AddReservedChargeRequest
	30,  // 31: network.ProverNetwork.GetBillingSummary:input_type -> types.GetBillingSummaryRequest
	31,  // 32: network.ProverNetwork.UpdatePrice:input_type -> types.UpdatePriceRequest
	32,  // 33: network.ProverNetwork.GetFilteredClusters:input_type -> types.GetFilteredClustersRequest
	33,  // 34: network.ProverNetwork.GetUsageSummary:input_type -> types.GetUsageSummaryRequest
	34,  // 35: network.ProverNetwork.Transfer:input_type -> types.TransferRequest
	35,  // 36: network.ProverNetwork.GetWithdrawParams:input_type -> types.GetWithdrawParamsRequest
	36,  // 37: network.ProverNetwork.Withdraw:input_type -> types.WithdrawRequest
	37,  // 38: network.ProverNetwork.GetFilteredReservations:input_type -> types.GetFilteredReservationsRequest
	38,  // 39: network.ProverNetwork.AddReservation:input_type -> types.AddReservationRequest
	39,  // 40: network.ProverNetwork.RemoveReservation:input_type -> types.RemoveReservationRequest
	40,  // 41: network.ProverNetwork.Bid:input_type -> types.BidRequest
	41,  // 42: network.ProverNetwork.Settle:input_type -> types.SettleRequest
	42,  // 43: network.ProverNetwork.GetProversByUptime:input_type -> types.GetProversByUptimeRequest
	43,  // 44: network.ProverNetwork.SignIn:input_type -> types.SignInRequest
	44,  // 45: network.ProverNetwork.GetOnboardedAccountsCount:input_type -> types.GetOnboardedAccountsCountRequest
	45,  // 46: network.ProverNetwork.GetFilteredOnboardedAccounts:input_type -> types.GetFilteredOnboardedAccountsRequest
	46,  // 47: network.ProverNetwork.GetLeaderboard:input_type -> types.GetLeaderboardRequest
	47,  // 48: network.ProverNetwork.GetLeaderboardStats:input_type -> types.GetLeaderboardStatsRequest
	48,  // 49: network.ProverNetwork.GetCodes:input_type -> types.GetCodesRequest
	49,  // 50: network.ProverNetwork.RedeemCode:input_type -> types.RedeemCodeRequest
	50,  // 51: network.ProverNetwork.ConnectTwitter:input_type -> types.ConnectTwitterRequest
	51,  // 52: network.ProverNetwork.CompleteOnboarding:input_type -> types.CompleteOnboardingRequest
	52,  // 53: network.ProverNetwork.SetUseTwitterHandle:input_type -> types.SetUseTwitterHandleRequest
	53,  // 54: network.ProverNetwork.SetUseTwitterImage:input_type -> types.SetUseTwitterImageRequest
	54,  // 55: network.ProverNetwork.RequestRandomProof:input_type -> types.RequestRandomProofRequest
	55,  // 56: network.ProverNetwork.SubmitCaptchaGame:input_type -> types.SubmitCaptchaGameRequest
	56,  // 57: network.ProverNetwork.RedeemStars:input_type -> types.RedeemStarsRequest
	57,  // 58: network.ProverNetwork.GetFlappyLeaderboard:input_type -> types.GetFlappyLeaderboardRequest
	58,  // 59: network.ProverNetwork.SetTurboHighScore:input_type -> types.SetTurboHighScoreRequest
	59,  // 60: network.ProverNetwork.SubmitQuizGame:input_type -> types.SubmitQuizGameRequest
	60,  // 61: network.ProverNetwork.GetTurboLeaderboard:input_type -> types.GetTurboLeaderboardRequest
	61,  // 62: network.ProverNetwork.SubmitEthBlockMetadata:input_type -> types.SubmitEthBlockMetadataRequest
	62,  // 63: network.ProverNetwork.GetFilteredEthBlockRequests:input_type -> types.GetFilteredEthBlockRequestsRequest
	63,  // 64: network.ProverNetwork.Set2048HighScore:input_type -> types.Set2048HighScoreRequest
	64,  // 65: network.ProverNetwork.SetVolleyballHighScore:input_type -> types.SetVolleyballHighScoreRequest
	65,  // 66: network.ProverNetwork.GetEthBlockRequestMetrics:input_type -> types.GetEthBlockRequestMetricsRequest
	66,  // 67: network.ProverNetwork.SetTurboTimeTrialHighScore:input_type -> types.SetTurboTimeTrialHighScoreRequest
	67,  // 68: network.ProverNetwork.SetCoinCrazeHighScore:input_type -> types.SetCoinCrazeHighScoreRequest
	68,  // 69: network.ProverNetwork.SetLeanHighScore:input_type -> types.SetLeanHighScoreRequest
	69,  // 70: network.ProverNetwork.SetFlowHighScore:input_type -> types.SetFlowHighScoreRequest
	70,  // 71: network.ProverNetwork.SetRollupHighScore:input_type -> types.SetRollupHighScoreRequest
	71,  // 72: network.ProverNetwork.GetPendingStars:input_type -> types.GetPendingStarsRequest
	72,  // 73: network.ProverNetwork.GetWhitelistStatus:input_type -> types.GetWhitelistStatusRequest
	73,  // 74: network.ProverNetwork.ClaimGpu:input_type -> types.ClaimGpuRequest
	74,  // 75: network.ProverNetwork.SetGpuVariant:input_type -> types.SetGpuVariantRequest
	75,  // 76: network.ProverNetwork.LinkWhitelistedTwitter:input_type -> types.LinkWhitelistedTwitterRequest
	76,  // 77: network.ProverNetwork.RetrieveProvingKey:input_type -> types.RetrieveProvingKeyRequest
	77,  // 78: network.ProverNetwork.LinkWhitelistedGithub:input_type -> types.LinkWhitelistedGithubRequest
	78,  // 79: network.ProverNetwork.LinkWhitelistedDiscord:input_type -> types.LinkWhitelistedDiscordRequest
	79,  // 80: network.ProverNetwork.GetProverLeaderboard:input_type -> types.GetProverLeaderboardRequest
	80,  // 81: network.ProverNetwork.GetFilteredGpus:input_type -> types.GetFilteredGpusRequest
	81,  // 82: network.ProverNetwork.SetGpuCoordinates:input_type -> types.SetGpuCoordinatesRequest
	82,  // 83: network.ProverNetwork.GetPoints:input_type -> types.GetPointsRequest
	83,  // 84: network.ProverNetwork.ProcessClicks:input_type -> types.ProcessClicksRequest
	84,  // 85: network.ProverNetwork.PurchaseUpgrade:input_type -> types.PurchaseUpgradeRequest
	85,  // 86: network.ProverNetwork.Bet:input_type -> types.BetRequest
	86,  // 87: network.ProverNetwork.GetContestDetails:input_type -> types.GetContestDetailsRequest
	87,  // 88: network.ProverNetwork.GetLatestContest:input_type -> types.GetLatestContestRequest
	88,  // 89: network.ProverNetwork.GetContestBettors:input_type -> types.GetContestBettorsRequest
	89,  // 90: network.ProverNetwork.GetGpuMetrics:input_type -> types.GetGpuMetricsRequest
	90,  // 91: network.ProverNetwork.GetFilteredProverActivity:input_type -> types.GetFilteredProverActivityRequest
	91,  // 92: network.ProverNetwork.GetProverMetrics:input_type -> types.GetProverMetricsRequest
	92,  // 93: network.ProverNetwork.GetFilteredBetHistory:input_type -> types.GetFilteredBetHistoryRequest
	93,  // 94: network.ProverNetwork.GetGpuTeamStats:input_type -> types.GetGpuTeamStatsRequest
	94,  // 95: network.ProverNetwork.GetConfigValues:input_type -> types.GetConfigValuesRequest
	95,  // 96: network.ProverNetwork.GetProverStats:input_type -> types.GetProverStatsRequest
	96,  // 97: network.ProverNetwork.GetFilteredProverStats:input_type -> types.GetFilteredProverStatsRequest
	97,  // 98: network.ProverNetwork.GetProverStatsDetail:input_type -> types.GetProverStatsDetailRequest
	98,  // 99: network.ProverNetwork.GetProverSearchResults:input_type -> types.GetProverSearchResultsRequest
	99,  // 100: network.ProverNetwork.GetFilteredBidHistory:input_type -> types.GetFilteredBidHistoryRequest
	100, // 101: network.ProverNetwork.GetTEEWhitelistStatus:input_type -> types.GetTEEWhitelistStatusRequest
	101, // 102: network.ProverNetwork.GetSettlementRequest:input_type -> types.GetSettlementRequestRequest
	102, // 103: network.ProverNetwork.GetFilteredSettlementRequests:input_type -> types.GetFilteredSettlementRequestsRequest
	103, // 104: network.ProverNetwork.GetFilteredProvers:input_type -> types.GetFilteredProversRequest
	104, // 105: network.ProverNetwork.GetProverStakeBalance:input_type -> types.GetProverStakeBalanceRequest
	105, // 106: network.ProverNetwork.GetFilteredStakerStakeBalanceLogs:input_type -> types.GetFilteredStakerStakeBalanceLogsRequest
	106, // 107: network.ProverNetwork.GetFilteredProverStakeBalanceLogs:input_type -> types.GetFilteredProverStakeBalanceLogsRequest
	107, // 108: network.ProverNetwork.GetDelegationParams:input_type -> types.GetDelegationParamsRequest
	108, // 109: network.ProverNetwork.SetDelegation:input_type -> types.SetDelegationRequest
	109, // 110: network.ProverNetwork.GetDelegation:input_type -> types.GetDelegationRequest
	110, // 111: network.ProverNetwork.GetFilteredWithdrawalReceipts:input_type -> types.GetFilteredWithdrawalReceiptsRequest
	111, // 112: network.ProverNetwork.RequestProof:output_type -> types.RequestProofResponse
	112, // 113: network.ProverNetwork.FulfillProof:output_type -> types.FulfillProofResponse
	113, // 114: network.ProverNetwork.ExecuteProof:output_type -> types.ExecuteProofResponse
	114, // 115: network.ProverNetwork.FailFulfillment:output_type -> types.FailFulfillmentResponse
	115, // 116: network.ProverNetwork.GetProofRequestStatus:output_type -> types.GetProofRequestStatusResponse
	116, // 117: network.ProverNetwork.GetProofRequestDetails:output_type -> types.GetProofRequestDetailsResponse
	117, // 118: network.ProverNetwork.GetFilteredProofRequests:output_type -> types.GetFilteredProofRequestsResponse
	118, // 119: network.ProverNetwork.SubscribeProofRequests:output_type -> types.ProofRequest
	119, // 120: network.ProverNetwork.GetSearchResults:output_type -> types.GetSearchResultsResponse
	120, // 121: network.ProverNetwork.GetProofRequestMetrics:output_type -> types.GetProofRequestMetricsResponse
	121, // 122: network.ProverNetwork.GetProofRequestGraph:output_type -> types.GetProofRequestGraphResponse
	122, // 123: network.ProverNetwork.GetAnalyticsGraphs:output_type -> types.GetAnalyticsGraphsResponse
	123, // 124: network.ProverNetwork.GetOverviewGraphs:output_type -> types.GetOverviewGraphsResponse
	124, // 125: network.ProverNetwork.GetProofRequestParams:output_type -> types.GetProofRequestParamsResponse
	125, // 126: network.ProverNetwork.GetNonce:output_type -> types.GetNonceResponse
	126, // 127: network.ProverNetwork.SetAccountName:output_type -> types.SetAccountNameResponse
	127, // 128: network.ProverNetwork.GetAccountName:output_type -> types.GetAccountNameResponse
	128, // 129: network.ProverNetwork.GetTermsSignature:output_type -> types.GetTermsSignatureResponse
	129, // 130: network.ProverNetwork.SetTermsSignature:output_type -> types.SetTermsSignatureResponse
	130, // 131: network.ProverNetwork.GetAccount:output_type -> types.GetAccountResponse
	131, // 132: network.ProverNetwork.GetOwner:output_type -> types.GetOwnerResponse
	132, // 133: network.ProverNetwork.GetProgram:output_type -> types.GetProgramResponse
	133, // 134: network.ProverNetwork.CreateProgram:output_type -> types.CreateProgramResponse
	134, // 135: network.ProverNetwork.SetProgramName:output_type -> types.SetProgramNameResponse
	135, // 136: network.ProverNetwork.GetBalance:output_type -> types.GetBalanceResponse
	136, // 137: network.ProverNetwork.GetFilteredBalanceLogs:output_type -> types.GetFilteredBalanceLogsResponse
	137, // 138: network.ProverNetwork.AddCredit:output_type -> types.AddCreditResponse
	138, // 139: network.ProverNetwork.GetLatestBridgeBlock:output_type -> types.GetLatestBridgeBlockResponse
	139, // 140: network.ProverNetwork.GetGasPriceEstimate:output_type -> types.GetGasPriceEstimateResponse
	140, // 141: network.ProverNetwork.GetTransactionDetails:output_type -> types.GetTransactionDetailsResponse
	141, // 142: network.ProverNetwork.AddReservedCharge:output_type -> types.AddReservedChargeResponse
	142, // 143: network.ProverNetwork.GetBillingSummary:output_type -> types.GetBillingSummaryResponse
	143, // 144: network.ProverNetwork.UpdatePrice:output_type -> types.UpdatePriceResponse
	144, // 145: network.ProverNetwork.GetFilteredClusters:output_type -> types.GetFilteredClustersResponse
	145, // 146: network.ProverNetwork.GetUsageSummary:output_type -> types.GetUsageSummaryResponse
	146, // 147: network.ProverNetwork.Transfer:output_type -> types.TransferResponse
	147, // 148: network.ProverNetwork.GetWithdrawParams:output_type -> types.GetWithdrawParamsResponse
	148, // 149: network.ProverNetwork.Withdraw:output_type -> types.WithdrawResponse
	149, // 150: network.ProverNetwork.GetFilteredReservations:output_type -> types.GetFilteredReservationsResponse
	150, // 151: network.ProverNetwork.AddReservation:output_type -> types.AddReservationResponse
	151, // 152: network.ProverNetwork.RemoveReservation:output_type -> types.RemoveReservationResponse
	152, // 153: network.ProverNetwork.Bid:output_type -> types.BidResponse
	153, // 154: network.ProverNetwork.Settle:output_type -> types.SettleResponse
	154, // 155: network.ProverNetwork.GetProversByUptime:output_type -> types.GetProversByUptimeResponse
	155, // 156: network.ProverNetwork.SignIn:output_type -> types.SignInResponse
	156, // 157: network.ProverNetwork.GetOnboardedAccountsCount:output_type -> types.GetOnboardedAccountsCountResponse
	157, // 158: network.ProverNetwork.GetFilteredOnboardedAccounts:output_type -> types.GetFilteredOnboardedAccountsResponse
	158, // 159: network.ProverNetwork.GetLeaderboard:output_type -> types.GetLeaderboardResponse
	159, // 160: network.ProverNetwork.GetLeaderboardStats:output_type -> types.GetLeaderboardStatsResponse
	160, // 161: network.ProverNetwork.GetCodes:output_type -> types.GetCodesResponse
	161, // 162: network.ProverNetwork.RedeemCode:output_type -> types.RedeemCodeResponse
	162, // 163: network.ProverNetwork.ConnectTwitter:output_type -> types.ConnectTwitterResponse
	163, // 164: network.ProverNetwork.CompleteOnboarding:output_type -> types.CompleteOnboardingResponse
	164, // 165: network.ProverNetwork.SetUseTwitterHandle:output_type -> types.SetUseTwitterHandleResponse
	165, // 166: network.ProverNetwork.SetUseTwitterImage:output_type -> types.SetUseTwitterImageResponse
	166, // 167: network.ProverNetwork.RequestRandomProof:output_type -> types.RequestRandomProofResponse
	167, // 168: network.ProverNetwork.SubmitCaptchaGame:output_type -> types.SubmitCaptchaGameResponse
	168, // 169: network.ProverNetwork.RedeemStars:output_type -> types.RedeemStarsResponse
	169, // 170: network.ProverNetwork.GetFlappyLeaderboard:output_type -> types.GetFlappyLeaderboardResponse
	170, // 171: network.ProverNetwork.SetTurboHighScore:output_type -> types.SetTurboHighScoreResponse
	171, // 172: network.ProverNetwork.SubmitQuizGame:output_type -> types.SubmitQuizGameResponse
	172, // 173: network.ProverNetwork.GetTurboLeaderboard:output_type -> types.GetTurboLeaderboardResponse
	173, // 174: network.ProverNetwork.SubmitEthBlockMetadata:output_type -> types.SubmitEthBlockMetadataResponse
	174, // 175: network.ProverNetwork.GetFilteredEthBlockRequests:output_type -> types.GetFilteredEthBlockRequestsResponse
	175, // 176: network.ProverNetwork.Set2048HighScore:output_type -> types.Set2048HighScoreResponse
	176, // 177: network.ProverNetwork.SetVolleyballHighScore:output_type -> types.SetVolleyballHighScoreResponse
	177, // 178: network.ProverNetwork.GetEthBlockRequestMetrics:output_type -> types.GetEthBlockRequestMetricsResponse
	178, // 179: network.ProverNetwork.SetTurboTimeTrialHighScore:output_type -> types.SetTurboTimeTrialHighScoreResponse
	179, // 180: network.ProverNetwork.SetCoinCrazeHighScore:output_type -> types.SetCoinCrazeHighScoreResponse
	180, // 181: network.ProverNetwork.SetLeanHighScore:output_type -> types.SetLeanHighScoreResponse
	181, // 182: network.ProverNetwork.SetFlowHighScore:output_type -> types.SetFlowHighScoreResponse
	182, // 183: network.ProverNetwork.SetRollupHighScore:output_type -> types.SetRollupHighScoreResponse
	183, // 184: network.ProverNetwork.GetPendingStars:output_type -> types.GetPendingStarsResponse
	184, // 185: network.ProverNetwork.GetWhitelistStatus:output_type -> types.GetWhitelistStatusResponse
	185, // 186: network.ProverNetwork.ClaimGpu:output_type -> types.ClaimGpuResponse
	186, // 187: network.ProverNetwork.SetGpuVariant:output_type -> types.SetGpuVariantResponse
	187, // 188: network.ProverNetwork.LinkWhitelistedTwitter:output_type -> types.LinkWhitelistedTwitterResponse
	188, // 189: network.ProverNetwork.RetrieveProvingKey:output_type -> types.RetrieveProvingKeyResponse
	189, // 190: network.ProverNetwork.LinkWhitelistedGithub:output_type -> types.LinkWhitelistedGithubResponse
	190, // 191: network.ProverNetwork.LinkWhitelistedDiscord:output_type -> types.LinkWhitelistedDiscordResponse
	191, // 192: network.ProverNetwork.GetProverLeaderboard:output_type -> types.GetProverLeaderboardResponse
	192, // 193: network.ProverNetwork.GetFilteredGpus:output_type -> types.GetFilteredGpusResponse
	193, // 194: network.ProverNetwork.SetGpuCoordinates:output_type -> types.SetGpuCoordinatesResponse
	194, // 195: network.ProverNetwork.GetPoints:output_type -> types.GetPointsResponse
	195, // 196: network.ProverNetwork.ProcessClicks:output_type -> types.ProcessClicksResponse
	196, // 197: network.ProverNetwork.PurchaseUpgrade:output_type -> types.PurchaseUpgradeResponse
	197, // 198: network.ProverNetwork.Bet:output_type -> types.BetResponse
	198, // 199: network.ProverNetwork.GetContestDetails:output_type -> types.GetContestDetailsResponse
	199, // 200: network.ProverNetwork.GetLatestContest:output_type -> types.GetLatestContestResponse
	200, // 201: network.ProverNetwork.GetContestBettors:output_type -> types.GetContestBettorsResponse
	201, // 202: network.ProverNetwork.GetGpuMetrics:output_type -> types.GetGpuMetricsResponse
	202, // 203: network.ProverNetwork.GetFilteredProverActivity:output_type -> types.GetFilteredProverActivityResponse
	203, // 204: network.ProverNetwork.GetProverMetrics:output_type -> types.GetProverMetricsResponse
	204, // 205: network.ProverNetwork.GetFilteredBetHistory:output_type -> types.GetFilteredBetHistoryResponse
	205, // 206: network.ProverNetwork.GetGpuTeamStats:output_type -> types.GetGpuTeamStatsResponse
	206, // 207: network.ProverNetwork.GetConfigValues:output_type -> types.GetConfigValuesResponse
	207, // 208: network.ProverNetwork.GetProverStats:output_type -> types.GetProverStatsResponse
	208, // 209: network.ProverNetwork.GetFilteredProverStats:output_type -> types.GetFilteredProverStatsResponse
	209, // 210: network.ProverNetwork.GetProverStatsDetail:output_type -> types.GetProverStatsDetailResponse
	210, // 211: network.ProverNetwork.GetProverSearchResults:output_type -> types.GetProverSearchResultsResponse
	211, // 212: network.ProverNetwork.GetFilteredBidHistory:output_type -> types.GetFilteredBidHistoryResponse
	212, // 213: network.ProverNetwork.GetTEEWhitelistStatus:output_type -> types.GetTEEWhitelistStatusResponse
	213, // 214: network.ProverNetwork.GetSettlementRequest:output_type -> types.GetSettlementRequestResponse
	214, // 215: network.ProverNetwork.GetFilteredSettlementRequests:output_type -> types.GetFilteredSettlementRequestsResponse
	215, // 216: network.ProverNetwork.GetFilteredProvers:output_type -> types.GetFilteredProversResponse
	216, // 217: network.ProverNetwork.GetProverStakeBalance:output_type -> types.GetProverStakeBalanceResponse
	217, // 218: network.ProverNetwork.GetFilteredStakerStakeBalanceLogs:output_type -> types.GetFilteredStakerStakeBalanceLogsResponse
	218, // 219: network.ProverNetwork.GetFilteredProverStakeBalanceLogs:output_type -> types.GetFilteredProverStakeBalanceLogsResponse
	219, // 220: network.ProverNetwork.GetDelegationParams:output_type -> types.GetDelegationParamsResponse
	220, // 221: network.ProverNetwork.SetDelegation:output_type -> types.SetDelegationResponse
	221, // 222: network.ProverNetwork.GetDelegation:output_type -> types.GetDelegationResponse
	222, // 223: network.ProverNetwork.GetFilteredWithdrawalReceipts:output_type -> types.GetFilteredWithdrawalReceiptsResponse
	112, // [112:224] is the sub-list for method output_type
	0,   // [0:112] is the sub-list for method input_type
	0,   // [0:0] is the sub-list for extension type_name
	0,   // [0:0] is the sub-list for extension extendee
	0,   // [0:0] is the sub-list for field type_name
}

func init() { file_network_proto_init() }
func file_network_proto_init() {
	if File_network_proto != nil {
		return
	}
	file_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_network_proto_rawDesc), len(file_network_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_network_proto_goTypes,
		DependencyIndexes: file_network_proto_depIdxs,
	}.Build()
	File_network_proto = out.File
	file_network_proto_goTypes = nil
	file_network_proto_depIdxs = nil
}
