name: ci
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build
        run: make build

  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Test
        run: go test -race ./...

  vet:
    name: Vet
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Vet
        run: go vet ./...

  fmt:
    name: Format
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: gofmt
        run: |
          unformatted=$(gofmt -l $(git ls-files '*.go'))
          if [[ -n "$unformatted" ]]; then
            echo "❌ The following files are not formatted. Run \`gofmt -w\`:"
            echo "$unformatted"
            exit 1
          fi
          echo "✅ All Go files are formatted."

  gen:
    name: Check generated files
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Generate files
        run: |
          make -B metrics.md
          go install golang.org/x/tools/cmd/stringer@latest
          go generate ./...
      - name: Ensure generated files are updated
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "❌ Error: Generated files are not up to date. Please run \`make -B metrics.md && go generate ./...\`."
            git status --porcelain
            git diff
            exit 1
          else
            echo "✅ Generated files are up to date."
          fi
