// Code generated by "stringer -type=Subsystem"; DO NOT EDIT.

package metrics

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RPC-0]
	_ = x[Sensor-1]
	_ = x[Heimdall-2]
	_ = x[System-3]
	_ = x[SPN-4]
}

const _Subsystem_name = "RPCSensorHeimdallSystemSPN"

var _Subsystem_index = [...]uint8{0, 3, 9, 17, 23, 26}

func (i Subsystem) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Subsystem_index)-1 {
		return "Subsystem(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Subsystem_name[_Subsystem_index[idx]:_Subsystem_index[idx+1]]
}
